### ISSUE TITLE
forgot a passcode: no way to reset it?

### ISSUE THREAD

**Issue by adrian-gierakowski** [liu044100/SmileTouchID#12]
Hi

If I setup a passcode and then forget it, there doesn't seem to be any way to reset it. If I delete the app and instal it again it still asks me for a password. Is there something I am doing wrong?

thanks!

**Comment by liu044100** [comment]
Hi @adrian-gierakowski , 

If your device support TouchID, it can easily reset passcode by using TouchID.

If your device does not support TouchID, sorry about that there is no way to reset passcode if you forget it.

Because the passcode was saved in the keychain, so even the app was deleted, the passcode will not be deleted and still in the keychain, when the app reinstalled, the app will use the passcode that was saved in the keychain.

If you just want to find the passcode in the keychain for debug or development, you can search this method  `+(BOOL)isSamePassword:(NSString *)userInput` , and uncomment the  `NSLog`.

**Comment by adrian-gierakowski** [comment]
@liu044100 : thank you for your quick reply

so if I understand it correctly for devices without TouchID its better to now use passcode at all since if the user looses his code he will be locked out of the app forever (unless he resets the device and doesn't restore it)?

**Comment by liu044100** [comment]
It is safe and no risk only use for devices that support TouchID, you can also extend this library for your needs by making a server that help the user to reset passcode.

**Comment by adrian-gierakowski** [comment]
ok, got it, thanks for your help!
