### ISSUE TITLE
AuthViewController close current modal views

### ISSUE THREAD

**Issue by tovfigh** [liu044100/SmileTouchID#16]
Hi, 

I am implementing SmileTouchID on my app, it´s a great library. 

I have several modal views in the app, and when in any of them I lock the phone, when unlocking the app from AuthViewController the state of the app is not the same, the previous modal views are dismissed.

Any idea what could be the reason?

Thanks

**Comment by liu044100** [comment]
Hi @tovfigh, 

Because AuthViewController is used by `presentViewController:animated:completion:`, if any view controller was presented before present AuthViewController, AuthViewController will not be presented, so  firstly, the library will dismiss previous modal views, then present AuthViewController.

**Comment by tovfigh** [comment]
Hi @liu044100 ,
Thanks for your answer.

**Comment by DoctorG** [comment]
I have the same problem.  My app is frequently on a modal view when entering data and screen times out.  So what do you do in this case to prevent modal view from being dismissed?

**Comment by liu044100** [comment]
@DoctorG Sorry for the late reply.

I have fixed it in a new version `0.1.6`, the new version will cache the modal view and present it again, you can use `pod update` and check whether it works.

**Comment by DoctorG** [comment]
You are the best. Thank you for sharing such a great library
